version: "3.7"

services:
  # 데이터베이스
    db:
      container_name: myStoryMysql
      image: tjseocld/mysql:8.0.29
      restart: always
      command: mysqld --default-authentication-plugin=mysql_native_password
      volumes:
        - ./my.cnf:/etc/my.cnf
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: myStory
      ports:
        - '3306:3306'

  # 서버
    web:
      container_name: tomcatServer
      restart: always
      environment:
      - "JAVA_OPTS=--add-opens java.base/java.lang.invoke=ALL-UNNAMED"
      links:
        - db
      image: tjseocld/tomcat:9.0.64
      volumes:
        - ./ROOT.war:/usr/local/tomcat/webapps/ROOT.war
        - ./tomcat/webapps:/usr/local/tomcat/webapps
      ports:
        - '8080:8080'

 # 클라이언트
    client:
      restart: always
      container_name: client
      image: tjseocld/mystory:latest
      links:
        - web
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ".:/app"
        - "/app/node_modules"
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=development
      stdin_open: true
      tty: true 

  # 젠킨스
    jenkins:
      container_name: jenkins
      build:
        context: .
        dockerfile: ./DockerfileJenkins
      image: jenkins/jenkins:lts-jdk11
      ports:
        - 18080:8080
      volumes:
        - ./jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      restart: always
      environment: 
            TZ: "Asia/Seoul"